### ISSUE TITLE
Connection to HEC-DSSVue jars

### ISSUE THREAD

**Issue by oliviabergmann** [mkoohafkan/dssrip2#9]
I am unable to connect to program files. I have attached my version of HEC-DSSVue and HEC-DSSVue jar availible. My path is correct so I am unsure of the issue. 

```{r}
# remotes::install_github("mkoohafkan/dssrip2",force = TRUE)
require(dssrip2)
options(dss.home = "C:/Program Files/HEC/HEC-DSSVue")
options(dss.monolith = FALSE)
dss_connect('C:/Program Files/HEC/HEC-DSSVue')
```
Error message:
Error in get_jars(dss_home, monolith) :
No matches found for HEC-DSSVue jars:
hec.jar
rma.jar
lookup.jar
hec-dssvue.+.jar
help/dssvueHelp.jar

Version of HEC-DSSVue:
![2023-05-17 13_45_31-Mail](https://github.com/mkoohafkan/dssrip2/assets/105610937/b40a1828-8200-40c2-bfaf-fbad22565599)

HEC-DSSVue jar availible:
![2023-05-17 13_46_29-jar](https://github.com/mkoohafkan/dssrip2/assets/105610937/6a2eaaec-f445-4fd6-a91b-4858812be910)
![2023-05-17 13_48_22-jar](https://github.com/mkoohafkan/dssrip2/assets/105610937/cb155905-e732-4ac3-915f-f47c0a6200a8)
![2023-05-17 13_49_10-jar](https://github.com/mkoohafkan/dssrip2/assets/105610937/9686a963-9fb7-4665-8979-161de624b21b)

**Comment by mkoohafkan** [comment]
Thanks for reporting. It looks like DSSVue 3.3.x may have reorganized or renamed some of the jars, and `dssrip2` is not expecting this. As the error message states, `dssrip2` is looking for `hec.jar`, `rma.jar`, `lookup.jar`, `hec-dssvue<version>.jar`,
and `help/dssvueHelp.jar` but these files do not seem to exist in the DSSVue 3.3.29 jar folder.

I may need to add support for specifying DSSVue versions. I will try installing DSSVue 3.3.29 try to figure out the changes.

In the meantime, have you tried installing monolith via `dss_install_monolith()`? It will grab the monolith version of the required jars and place them in a separate folder. They will not conflict with any DSSVue installations.

**Comment by jvandens** [comment]
Hello, I have the same issue as @oliviabergmann with the DSSVue connection, I tried using the `dss_install_monolith()` initially, but get the following SSL error 
```
> dss_install_monolith()
Error in file(con, "r") : 
  cannot open the connection to 'https://repo.maven.apache.org/maven2/com/google/flogger/flogger/0.7.4/flogger-0.7.4.jar.sha1'
In addition: Warning message:
In file(con, "r") :
  URL 'https://repo.maven.apache.org/maven2/com/google/flogger/flogger/0.7.4/flogger-0.7.4.jar.sha1': status was 'SSL connect error'
```
However, I think this issue is mostly how our corporate network controls SSL connections so might not be a `dssrip2` problem.  

Is there an alternative method to manually download the monolith files and point `dssrip2` to them?  That might work as a workaround for now.

**Comment by mkoohafkan** [comment]
@jvandens I pushed a [new branch](https://github.com/mkoohafkan/dssrip2/tree/monolith_assets) that should give you the functionality you need to try manually installing the jars. Install that branch and run

```r
dssrip2:::monolith_assets(system.file("requirements.yaml", package = "dssrip2"), FALSE)
```

**Comment by jvandens** [comment]
Thanks @mkoohafkan .  I tried doing the above but it's still giving me an SSL issue.  Here is what I did:

```
remotes::install_github("mkoohafkan/dssrip2",
                        ref = "monolith_assets",
                        force = TRUE)

Downloading GitHub repo mkoohafkan/dssrip2@monolith_assets
....
```

which completed successfully. But when I do:
```
dssrip2:::monolith_assets(system.file("requirements.yaml", package = "dssrip2"), FALSE)
```
I get:
```
> dssrip2:::monolith_assets(system.file("requirements.yaml", package = "dssrip2"), FALSE)
Error in file(con, "r") : 
  cannot open the connection to 'https://repo.maven.apache.org/maven2/com/google/flogger/flogger/0.7.4/flogger-0.7.4.jar.sha1'
In addition: Warning message:
In file(con, "r") :
  URL 'https://repo.maven.apache.org/maven2/com/google/flogger/flogger/0.7.4/flogger-0.7.4.jar.sha1': status was 'SSL connect error'
```

So it looks like it's still trying to grab some jar files from the internet.  FYI, I can manually go to that URL and downloaded the flogger.jar file, so is there someplace I can just put that jar file (and perhaps others from my HECDSSVue install dir) and point dssrip2 to them?

Thanks again.

**Comment by mkoohafkan** [comment]
@jvandens I forgot that the sha1 validation for the Maven resources are files rather than just strings, so it still isn't getting to the point where it is returning the list of resources. I am going to try a different approach to the file downloads so I'd still appreciate you testing it when I push the changes, but in the meantime here is the full list of jar files:

- https://repo.maven.apache.org/maven2/com/google/flogger/flogger-system-backend/0.7.4/flogger-system-backend-0.7.4.jar
- https://repo.maven.apache.org/maven2/com/google/flogger/flogger/0.7.4/flogger-0.7.4.jar
- https://www.hec.usace.army.mil/nexus/repository/maven-releases/mil/army/usace/hec/hec-monolith-compat/3.3.16/hec-monolith-compat-3.3.16.jar
- https://www.hec.usace.army.mil/nexus/repository/maven-releases/mil/army/usace/hec/hec-monolith/3.3.16/hec-monolith-3.3.16.jar
- https://www.hec.usace.army.mil/nexus/repository/maven-releases/mil/army/usace/hec/hec-nucleus-data/2.0.1/hec-nucleus-data-2.0.1.jar
- https://www.hec.usace.army.mil/nexus/repository/maven-releases/mil/army/usace/hec/hec-nucleus-metadata/2.0.1/hec-nucleus-metadata-2.0.1.jar
- https://www.hec.usace.army.mil/nexus/repository/maven-releases/mil/army/usace/hec/hecnf/6.0.00.100/hecnf-6.0.00.100.jar
- https://www.hec.usace.army.mil/nexus/repository/maven-releases/mil/army/usace/hec/javaHeclib/7-IQ-11-win-x86_64/javaHeclib-7-IQ-11-win-x86_64.zip

**Comment by mkoohafkan** [comment]
@jvandens I would not be surprised if you run into similar issues with other packages in the future (or write your own scripts to do web scraping etc.). In general using the package [`curl`](https://cran.r-project.org/package=curl) and/or packages that depend on it (e.g., [`httr`](https://cran.r-project.org/package=httr)) should help you avoid issues because they [default to using the Windows Certificate Store](https://cran.r-project.org/web/packages/curl/vignettes/windows.html) on windows machines and thus can access your office's self-signed certificates, whereas base R uses OpenSSL and will not automatically have access to said certificates.

**Comment by mkoohafkan** [comment]
@oliviabergmann did you try the monolith approach? Is there a specific reason for wanting to connect to a DSSVue installation, or is it just a matter of convenience?

**Comment by mkoohafkan** [comment]
Closing due to no response from original poster. See #12 for further information on DSSVue support.
